### ISSUE TITLE
Replace Kaitai-generated parser with a handwritten one

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/mishegos#150]
Per #149: Kaitai is a bit of a mess to install reliably outside of the Docker container.

The cohorts format is simple enough; we should probably just rewrite `mish2jsonl` in C and re-use Mishegos's structure definitions in it.

**Comment by sabastiaan** [comment]
Regarding the binary format,
Currently we save the path to the .so in each output, wouldn't it be better to:

1. change the path to only include <worker_name>.so
2. promote the text of the worker_name to the header and either leave naming implicit or through an index?

**Comment by woodruffw** [comment]
Yes, both of those are good suggestions -- the presence of the full `.so` path is a bit of a historical oversight. Workers should be uniquely identified by their `worker_name` and *only* their `worker_name`.

> As far the length fields, they currently are u64, wouldn't u32 (or u16 for that matter) be sufficient?

I think so, yes. If I remember right my original reason for making them u64s was alignment, but most things in mishegos end up packed anyways. Most of those fields can definitely be u32/u16 and possibly even u8.

**Comment by sabastiaan** [comment]
If those changes were to go through, would this end up causing any issues with other parts? There are asserts of for example output_slots being 1050 but I'm not sure if that was only there because of the serialization.

**Comment by woodruffw** [comment]
> If those changes were to go through, would this end up causing any issues with other parts? There are asserts of for example output_slots being 1050 but I'm not sure if that was only there because of the serialization.

I don't _think_ so -- the only structures and alignments that should matter for serialization are the ones that get dumped directly. The size of the `output_slot` was more about shared memory alignment, but it wasn't particularly well justified either (we should probably trust the compiler).

**Comment by woodruffw** [comment]
#162.
